---
title: "Introduction to R"
author: "Louisa H. Smith"
date: "September-October 2019"
output:
  html_document:
    css: "lab.css"
    theme: spacelab
    highlight: kate
---

## [Syllabus](syllabus.html)
All sessions will take place in FXB G-12 from 2-3:30 pm.

## Schedule: {.tabset .tabset-fade .tabset-pills}

### Day 1 (9/6/19)
#### Figures

View the slides [here](slides/Day1-slides.html) (or download as [pdf](slides/Day1-slides.pdf))

Download the scripts and data [here](https://github.com/louisahsmith/r-materials-F19/blob/master/day1.zip?raw=true).

If you're having trouble with R on your own machine, click [this link](https://rstudio.cloud/project/492066) and sign up for a free RStudio cloud account. You'll be able to access all the materials directly.

Some `ggplot2` resources mentioned in the slides:

- [Cheat sheet](https://content.cdntwrk.com/files/aT0xMTI0Mjk2JnY9MSZpc3N1ZU5hbWU9ZGF0YS12aXN1YWxpemF0aW9uLTItMSZjbWQ9ZCZzaWc9MWVkMDFhMDExMjA1OTlmZTQ0NWY0OWVmYmQwOWQ1NDA%253D)
- [Catalog](http://shiny.stat.ubc.ca/r-graph-catalog/)
- [Cookbook](http://www.cookbook-r.com/Graphs/)
- [Official package reference](https://ggplot2.tidyverse.org/index.html)

You can watch a video of class [here](https://harvard.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=f46b735f-1b8f-4c22-a724-aabe00fd2998).

Download the [solution scripts](https://github.com/louisahsmith/r-materials-F19/blob/master/day1-sols.zip?raw=true).

### Day 2 (9/13/19)
#### Selecting, filtering, and mutating

View the slides [here](slides/Day2-slides.html) (or download as [pdf](slides/Day2-slides.pdf)).

Download the scripts and data [here](https://github.com/louisahsmith/r-materials-F19/blob/master/day2.zip?raw=true).

Open the project in RStudio Cloud [here](https://rstudio.cloud/project/520117).

Resources:

- Here's an [entire paper](https://peerj.com/preprints/3163/) about working with factors in R.
- [`forcats` cheat sheet](https://content.cdntwrk.com/files/aT0xMTI0MjU3JnY9MSZpc3N1ZU5hbWU9ZmFjdG9ycyZjbWQ9ZCZzaWc9ZjhhOTkzMTNlZGIxYTQ1ZGM4NTM4OWZiOTVlNzE3YjI%253D)

You can watch a video of class [here](https://harvard.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d77d2fa7-6418-44b2-a50b-aabe00fd29e8).

Download the [solution script](https://raw.githubusercontent.com/louisahsmith/intro-to-R/master/day2/day2-script-sols.R).

### Day 3 (9/27/19)

#### Grouping and tables

### Day 4 (10/11/19)
#### Functions

### Day 5 (10/18/19)
#### Analyze your data